import Footer from "@/components/shared/Footer";
import Header from "@/components/shared/Header";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FoodBeast",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-4xl mx-auto p-4">
          <Header />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
